export type { Project } from "tsgo-typescript/unstable/async"
export type {
  ArrowFunction,
  BinaryExpression,
  Block,
  CallExpression,
  CatchClause,
  ConstructorDeclaration,
  FunctionDeclaration,
  FunctionExpression,
  GetAccessorDeclaration,
  Identifier,
  MethodDeclaration,
  ModifierLike,
  Node,
  ParameterDeclaration,
  PropertyAccessExpression,
  PropertyAssignment,
  PropertyDeclaration,
  SetAccessorDeclaration,
  SourceFile,
  VariableDeclaration,
  VoidExpression,
} from "tsgo-typescript/unstable/ast"
export { SyntaxKind } from "tsgo-typescript/unstable/ast"
export {
  isArrowFunction,
  isBinaryExpression,
  isBlock,
  isCallExpression,
  isCatchClause,
  isConstructorDeclaration,
  isExportAssignment,
  isExpressionStatement,
  isFunctionDeclaration,
  isFunctionExpression,
  isGetAccessorDeclaration,
  isIdentifier,
  isMethodDeclaration,
  isObjectLiteralExpression,
  isPropertyAccessExpression,
  isPropertyAssignment,
  isPropertyDeclaration,
  isSetAccessorDeclaration,
  isSourceFile,
  isStringLiteral,
  isVariableDeclaration,
  isVoidExpression,
} from "tsgo-typescript/unstable/ast/is"
export { forEachLeadingCommentRange } from "tsgo-typescript/unstable/ast/scanner"
export { isMethodSignatureDeclaration as isMethodSignature } from "tsgo-typescript/unstable/ast/is"
export type { MethodSignatureDeclaration as MethodSignature } from "tsgo-typescript/unstable/ast"
