export {
  decodeProjectModuleManifest,
  fingerprintProjectModuleManifest,
  type PackageProjectModuleRef,
  type ProjectModuleManifest,
  type ProjectModuleRef,
  type ProjectModuleRefConfig,
  type RepoLocalProjectModuleRef,
  type WorkspaceProjectModuleRef,
} from "./manifest.js"

export {
  appendProjectModuleDecision,
  defineProcessor,
  defineProjectModule,
  type AnyProjectModuleProcessorDefinition,
  type DefinedProjectModule,
  type ProjectModuleDecisionInput,
  type ProjectModuleDefinitionInput,
  type ProjectModuleProcessor,
  type ProjectModuleProcessorDefinition,
  type ProjectModuleProcessorRuntime,
} from "./definition.js"

export {
  addPolicyTag,
  addSourceCategory,
  classifyArchitectureRole,
  classifyArchitecturalTier,
  classifyTypeScriptNoop,
  markTypeScriptExportPublicEntrypoint,
  nameTypeScriptCallbackContext,
  tuneTypeScriptUnsafeType,
  tuneTypeScriptUnfinishedImplementation,
  type AddPolicyTagOptions,
  type AddSourceCategoryOptions,
  type ClassifyArchitectureRoleOptions,
  type ClassifyArchitecturalTierOptions,
  type ClassifyTypeScriptNoopOptions,
  type MarkTypeScriptPublicEntrypointOptions,
  type NameTypeScriptCallbackContextOptions,
  type TuneTypeScriptUnsafeTypeOptions,
  type TuneTypeScriptUnfinishedImplementationOptions,
} from "./helpers.js"

export {
  tuneFactorPolicy,
  tuneTypeScriptCloneGroup,
  tuneTypeScriptDependencyVersion,
  tuneTypeScriptNesting,
  tuneTypeScriptSize,
  tuneTypeScriptTypeCoupling,
  type TuneFactorPolicyOptions,
  type TuneTypeScriptCloneGroupOptions,
  type TuneTypeScriptNestingOptions,
  type TuneTypeScriptSizeOptions,
} from "./factor-policy-helper.js"

export {
  loadEnabledProjectModules,
  loadProjectModuleRef,
} from "./loader.js"
export type { ProjectModuleLoadOptions } from "./loader-types.js"

export {
  ARCHITECTURE_ROLE_METADATA_KEY,
  ARCHITECTURAL_TIER_METADATA_KEY,
  POLICY_TAGS_METADATA_KEY,
  readArchitectureRole,
  isArchitecturalTier,
  readArchitecturalTier,
  readPolicyTags,
  withArchitectureRoleMetadata,
  withArchitecturalTierMetadata,
  withPolicyTagMetadata,
  withPolicyTagsMetadata,
  fingerprintProjectModule,
  makeResolvedCalibrationContext,
  type ActiveProjectModule,
  type ArchitectureRole,
  type ArchitecturalTier,
  type AnyCalibrationProcessor,
  type CalibrationConfidence,
  type CalibrationDecision,
  type CalibrationEvidenceRef,
  type CalibrationProcessorRole,
  type CalibrationSlotId,
  type CalibrationSlotInput,
  type CalibrationSlotOutput,
  type CalibrationSlotResult,
  type ProjectModuleContribution,
  type ProjectModuleDescriptor,
  type ProjectModuleScope,
  type PolicyTag,
  type RepoFacts,
  type ResolvedCalibrationContext,
  type SourceCategory,
  type TypeScriptCallbackContextNameValue,
  type TypeScriptCallExpressionFact,
  type TypeScriptCloneGroupPolicyValue,
  type TypeScriptDependencyVersionPolicyValue,
  type TypeScriptExportDeclarationFact,
  type TypeScriptExportReachabilityValue,
  type TypeScriptExportSpecifierFact,
  type TypeScriptImportBindingFact,
  type TypeScriptLocalBindingFact,
  type TypeScriptNoopClassificationValue,
  type TypeScriptNestingPolicyValue,
  type TypeScriptSizePolicyValue,
  type TypeScriptTypeCouplingPolicyValue,
  type TypeScriptUnsafeTypePolicyValue,
  type TypeScriptUnfinishedImplementationPolicyValue,
} from "@skastr0/pulsar-core/calibration"
