import { describe, expect, test } from "bun:test"
import { Effect, Layer } from "effect"
import {
  CalibrationContextTag,
  appendCalibrationDecision,
  defineCalibrationProcessor,
  makeResolvedCalibrationContext,
  readArchitectureRole,
  readArchitecturalTier,
  readPolicyTags,
  type RepoFacts,
  withArchitectureRoleMetadata,
  withArchitecturalTierMetadata,
  withPolicyTagMetadata,
} from "../calibration.js"
import {
  classifyFilePath,
  isProductionSourcePath,
} from "../file-taxonomy.js"

const repoFacts: RepoFacts = {
  repoRoot: "/repo",
  fingerprint: "repo-facts-v1",
  detectedTechnologies: ["typescript"],
  sourceExtensions: [".ts"],
}

const classifyCategories = (
  filePath: string,
  options?: Parameters<typeof classifyFilePath>[1],
): ReadonlyArray<string> =>
  Effect.runSync(
    classifyFilePath(filePath, options).pipe(
      Effect.map((result) => result.value.categories),
    ),
  )

describe("file taxonomy", () => {
  test("default classification identifies production, tests, generated, and examples", () => {
    expect(classifyCategories("src/index.ts", { sourceExtensions: [".ts", ".tsx"] })).toEqual([
      "production_source",
    ])
    expect(
      classifyCategories("src/index.test.ts", { sourceExtensions: [".ts", ".tsx"] }),
    ).toContain("test_code")
    expect(
      classifyCategories("src/_generated/api.ts", { sourceExtensions: [".ts", ".tsx"] }),
    ).toContain("generated")
    expect(classifyCategories("examples/demo.ts", { sourceExtensions: [".ts", ".tsx"] })).toContain(
      "example",
    )
  })

  test("default classification preserves taxonomy rule behavior", () => {
    const sourceOptions = { sourceExtensions: [".ts", ".tsx"] }
    const examples = [
      ["node_modules/pkg/index.ts", ["dependency"]],
      ["dist/index.js", ["build_artifact"]],
      ["src/service.generated.ts", ["generated"]],
      ["docs/readme.md", ["documentation"]],
      ["src/component.stories.tsx", ["stories"]],
      ["src/types.d.ts", ["declaration"]],
      ["vite.config.ts", ["config_tooling"]],
      [".github/workflows/ci.yml", ["hidden_tooling"]],
      ["src/test-utils.ts", ["test_utility"]],
      ["src/unit.spec.ts", ["test_code"]],
      ["src/fixture/example.test.ts", ["example", "test_code"]],
      ["README.md", ["unknown"]],
    ] as const

    for (const [path, categories] of examples) {
      expect(classifyCategories(path, sourceOptions)).toEqual(categories)
    }
  })

  test("classification runs project module taxonomy processors when provided", async () => {
    const processor = defineCalibrationProcessor({
      id: "scratch-taxonomy",
      moduleId: "acme.project",
      moduleVersion: "1.0.0",
      slot: "taxonomy.file-classifier",
      role: "filter",
      priority: 10,
      fingerprint: "scratch-taxonomy-v1",
      process: (current) =>
        Effect.sync(() => {
          if (!current.value.path.endsWith("src/scratch.ts")) return current
          return appendCalibrationDecision(
            current,
            {
              moduleId: "acme.project",
              processorId: "scratch-taxonomy",
              slot: "taxonomy.file-classifier",
              action: "classify-generated",
              confidence: "medium",
              reason: "Project scratch source is generated by local tooling",
              evidence: [{ kind: "path", value: current.value.path }],
            },
            {
              ...current.value,
              categories: [...current.value.categories, "generated"],
            },
          )
        }),
    })
    const context = makeResolvedCalibrationContext({
      repoFacts,
      processors: [processor],
    })

    const classified = await Effect.runPromise(
      classifyFilePath("src/scratch.ts", { sourceExtensions: [".ts"] }).pipe(
        Effect.provide(Layer.succeed(CalibrationContextTag, context)),
      ),
    )
    const isProduction = await Effect.runPromise(
      isProductionSourcePath("src/scratch.ts", { sourceExtensions: [".ts"] }).pipe(
        Effect.provide(Layer.succeed(CalibrationContextTag, context)),
      ),
    )

    expect(classified.value.categories).toEqual(["generated", "production_source"])
    expect(classified.decisions[0]?.processorId).toBe("scratch-taxonomy")
    expect(isProduction).toBe(false)
  })

  test("neutral architecture role and policy tag helpers preserve repo-defined values", () => {
    const classified = withPolicyTagMetadata(
      withArchitectureRoleMetadata(
        { path: "src/domain/user.ts", categories: ["production_source"] as const },
        "domain-boundary",
        { source: "test", policy_tags: ["owner-reviewed"] },
      ),
      "runtime-owned",
    )

    expect(readArchitectureRole(classified.metadata)).toBe("domain-boundary")
    expect(readPolicyTags(classified.metadata)).toEqual([
      "owner-reviewed",
      "runtime-owned",
    ])
    expect(classified.metadata?.source).toBe("test")
    expect(readArchitectureRole({ architecture_role: "" })).toBeUndefined()
    expect(
      withArchitectureRoleMetadata(
        { path: "src/blank.ts", categories: ["production_source"] as const },
        "  ",
      ).metadata?.architecture_role,
    ).toBeUndefined()
    expect(readPolicyTags({ policy_tags: ["domain", "domain", "", 1] })).toEqual([
      "domain",
    ])
  })

  test("architectural tier metadata helpers remain available for compatibility", () => {
    const classified = withArchitecturalTierMetadata(
      { path: "src/adapter.ts", categories: ["production_source"] as const },
      "integration",
      { source: "test" },
    )

    expect(readArchitecturalTier(classified.metadata)).toBe("integration")
    expect(classified.metadata?.source).toBe("test")
    expect(readArchitecturalTier({ architectural_tier: "not-a-tier" })).toBeUndefined()
  })
})
