import { describe, expect, test } from "bun:test"
import { Effect, Layer } from "effect"
import {
  CalibrationContextTag,
  appendCalibrationDecision,
  defineCalibrationProcessor,
  makeResolvedCalibrationContext,
  type RepoFacts,
} from "../calibration.js"
import {
  classifyFilePath,
  classifyFilePathDefault,
  isProductionSourcePath,
} from "../file-taxonomy.js"

const repoFacts: RepoFacts = {
  repoRoot: "/repo",
  fingerprint: "repo-facts-v1",
  detectedTechnologies: ["typescript"],
  sourceExtensions: [".ts"],
}

describe("file taxonomy", () => {
  test("default classification identifies production, tests, generated, and examples", () => {
    expect(
      classifyFilePathDefault("src/index.ts", { sourceExtensions: [".ts", ".tsx"] }),
    ).toEqual(["production_source"])
    expect(
      classifyFilePathDefault("src/index.test.ts", { sourceExtensions: [".ts", ".tsx"] }),
    ).toContain("test_code")
    expect(
      classifyFilePathDefault("src/_generated/api.ts", { sourceExtensions: [".ts", ".tsx"] }),
    ).toContain("generated")
    expect(
      classifyFilePathDefault("examples/demo.ts", { sourceExtensions: [".ts", ".tsx"] }),
    ).toContain("example")
  })

  test("classification runs project module taxonomy processors when provided", async () => {
    const processor = defineCalibrationProcessor({
      id: "scratch-taxonomy",
      moduleId: "acme.project",
      moduleVersion: "1.0.0",
      slot: "taxonomy.file-classifier",
      role: "filter",
      priority: 10,
      fingerprint: "scratch-taxonomy-v1",
      process: (current) =>
        Effect.sync(() => {
          if (!current.value.path.endsWith("src/scratch.ts")) return current
          return appendCalibrationDecision(
            current,
            {
              moduleId: "acme.project",
              processorId: "scratch-taxonomy",
              slot: "taxonomy.file-classifier",
              action: "classify-generated",
              confidence: "medium",
              reason: "Project scratch source is generated by local tooling",
              evidence: [{ kind: "path", value: current.value.path }],
            },
            {
              ...current.value,
              categories: [...current.value.categories, "generated"],
            },
          )
        }),
    })
    const context = makeResolvedCalibrationContext({
      repoFacts,
      processors: [processor],
    })

    const classified = await Effect.runPromise(
      classifyFilePath("src/scratch.ts", { sourceExtensions: [".ts"] }).pipe(
        Effect.provide(Layer.succeed(CalibrationContextTag, context)),
      ),
    )
    const isProduction = await Effect.runPromise(
      isProductionSourcePath("src/scratch.ts", { sourceExtensions: [".ts"] }).pipe(
        Effect.provide(Layer.succeed(CalibrationContextTag, context)),
      ),
    )

    expect(classified.value.categories).toEqual(["generated", "production_source"])
    expect(classified.decisions[0]?.processorId).toBe("scratch-taxonomy")
    expect(isProduction).toBe(false)
  })
})
