import { pendingSignalContract, type SignalContract } from "./signal-contract.js"

export const TS_SIGNAL_CONTRACTS: ReadonlyArray<SignalContract> = [
  pendingSignalContract("TS-LD-01-cyclomatic-complexity"),
  pendingSignalContract("TS-LD-02-function-size-distribution"),
  pendingSignalContract("TS-LD-03-nesting-depth"),
  pendingSignalContract("TS-LD-04-naming-conventions"),
  pendingSignalContract("TS-LD-05-domain-term-consistency"),
  pendingSignalContract("TS-AD-01-boundary-violations"),
  pendingSignalContract("TS-AD-02-circular-dependencies"),
  pendingSignalContract("TS-AD-03-reexport-depth"),
  pendingSignalContract("TS-AD-04-boundary-parser-coverage"),
  pendingSignalContract("TS-AD-05-boundary-trust-breach"),
  pendingSignalContract("TS-DE-01-type-level-coupling"),
  pendingSignalContract("TS-DE-02-fan-in-fan-out"),
  pendingSignalContract("TS-DE-03-propagation-cost"),
  pendingSignalContract("TS-DE-04-package-dependency-health"),
  pendingSignalContract("TS-DE-05-duplicate-dependency-versions"),
  pendingSignalContract("TS-AB-01-public-export-surface"),
  pendingSignalContract("TS-AB-02-unused-exports"),
  pendingSignalContract("TS-AB-03-type-indirection-depth"),
  pendingSignalContract("TS-AB-04-interface-implementation-ratio"),
  pendingSignalContract("TS-AB-05-generic-proliferation"),
  pendingSignalContract("TS-LD-06-annotation-coverage"),
  pendingSignalContract("TS-LD-07-unsafe-type-erosion"),
  pendingSignalContract("TS-LD-08-exhaustiveness-erosion"),
  pendingSignalContract("TS-LD-09-error-channel-opacity"),
  pendingSignalContract("TS-RP-01-hotspots"),
  pendingSignalContract("TS-SL-01-duplication"),
  pendingSignalContract("TS-SL-03-suppressions"),
  pendingSignalContract("TS-SL-04-unfinished-implementations"),
  pendingSignalContract("TS-RP-02-pr-size"),
  pendingSignalContract("TS-SL-02-inconsistent-clones"),
]
