/**
 * @taste-codec/rs-pack — Rust signal pack scaffold.
 */

export const RS_PACK_VERSION = "0.0.0" as const

export * from "./cargo-metadata.js"
export * from "./lock-file.js"
export * from "./pack.js"
export * from "./project.js"
export * from "./rust-analysis.js"
export * from "./syn-walker.js"
export * from "./signals/shared-churn-01.js"
export * from "./signals/shared-02-bus-factor.js"
export * from "./signals/shared-03-churn-rate.js"
export * from "./signals/rs-ad-01-visibility-surface.js"
export * from "./signals/rs-ad-02-crate-boundaries.js"
export * from "./signals/rs-ad-03-circular-crate-deps.js"
export * from "./signals/rs-de-01-trait-coupling.js"
export * from "./signals/rs-de-02-dep-tree.js"
export * from "./signals/rs-de-03-feature-flags.js"
export * from "./signals/rs-de-04-fan-in-fan-out.js"
export * from "./signals/rs-ab-01-unused-pub.js"
export * from "./signals/rs-ab-02-trait-object-depth.js"
export * from "./signals/rs-ab-03-generic-proliferation.js"
export * from "./signals/rs-ab-04-derive-density.js"
export * from "./signals/rs-ld-01-unsafe.js"
export * from "./signals/rs-ld-02-lifetimes.js"
export * from "./signals/rs-ld-03-match-catch-all.js"
export * from "./signals/rs-ld-04-error-granularity.js"
export * from "./signals/rs-ld-05-complexity.js"
export * from "./signals/rs-ld-06-domain-terms.js"
export * from "./signals/rs-sl-01-duplication.js"
export * from "./signals/rs-sl-02-suppressions.js"
export * from "./signals/rs-sl-03-unwrap-expect.js"
export * from "./signals/rs-sl-04-clone-abuse.js"
export * from "./signals/rs-rp-01-hotspots.js"
export * from "./signals/rs-rp-02-compile-time.js"
export * from "./signals/rs-rp-03-pr-size.js"
