import { Schema } from "effect"

export const TsSl04Config = Schema.Struct({
  exclude_globs: Schema.Array(Schema.String),
  test_globs: Schema.Array(Schema.String),
  top_n_diagnostics: Schema.Number,
  hard_gate_production: Schema.Boolean,
  include_test_stubs: Schema.Boolean,
})
export type TsSl04Config = typeof TsSl04Config.Type

export const defaultTsSl04Config: TsSl04Config = {
  exclude_globs: [
    "**/node_modules/**",
    "**/dist/**",
    "**/.turbo/**",
    "**/vendor/**",
    "**/gen/**",
    "**/*.gen.ts",
    "**/*.gen.tsx",
    "**/*.generated.ts",
    "**/*.generated.tsx",
    "**/.storybook/**",
    "**/sst-env.d.ts",
    "example/**",
    "**/example/**",
    "examples/**",
    "**/examples/**",
    "demo/**",
    "**/demo/**",
    "demos/**",
    "**/demos/**",
    "private-demos/**",
    "**/private-demos/**",
    "fixture/**",
    "**/fixture/**",
    "fixtures/**",
    "**/fixtures/**",
    "sample/**",
    "**/sample/**",
    "samples/**",
    "**/samples/**",
    "spec/**",
    "**/spec/**",
    "specs/**",
    "**/specs/**",
    "sdk-samples/**",
    "**/sdk-samples/**",
    "template/**",
    "**/template/**",
    "templates/**",
    "**/templates/**",
  ],
  test_globs: [
    "**/*.test.ts",
    "**/*.test.tsx",
    "**/*.spec.ts",
    "**/*.spec.tsx",
    "**/*.stories.ts",
    "**/*.stories.tsx",
    "**/__tests__/**",
    "**/test/**",
    "**/tests/**",
    "**/test-support/**",
    "**/test-helpers/**",
    "**/test-mocks/**",
    "**/test-harness/**",
    "**/*test-support.ts",
    "**/*test-support.tsx",
    "**/*.test-support.ts",
    "**/*.test-support.tsx",
    "**/test-helpers.ts",
    "**/*test-helpers.ts",
    "**/*test-helpers.tsx",
    "**/*.test-helpers.ts",
    "**/*.test-helpers.tsx",
    "**/test-mocks.ts",
    "**/*mock.ts",
    "**/*mock.tsx",
    "**/mock*.ts",
    "**/mock*.tsx",
    "**/*test-mocks.ts",
    "**/*test-mocks.tsx",
    "**/*mocks.ts",
    "**/*mocks.tsx",
    "**/*.test-mocks.ts",
    "**/*.test-mocks.tsx",
    "**/test-harness.ts",
    "**/*harness.ts",
    "**/*harness.tsx",
    "**/*test-harness.ts",
    "**/*test-harness.tsx",
    "**/*.harness.ts",
    "**/*.harness.tsx",
    "**/*.test-harness.ts",
    "**/*.test-harness.tsx",
    "**/test-runtime.ts",
    "**/*test-runtime.ts",
    "**/*test-runtime.tsx",
    "**/*.test-runtime.ts",
    "**/*.test-runtime.tsx",
    "**/*test-runtime*.ts",
    "**/*test-runtime*.tsx",
    "**/happydom.ts",
  ],
  top_n_diagnostics: 20,
  hard_gate_production: true,
  include_test_stubs: false,
}
